// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snlircwlwryhhdhddhwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNubGlyY3dsd3J5aGhkaGRkaHdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NDYzMjgsImV4cCI6MjA2ODIyMjMyOH0.iifTx_gUeESWTRCFSBrDBa9gT2p19t2SoJt9o1wQ0gU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});